<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OSDC.Drilling.EarthGravity.Model</RootNamespace>
    <Authors>Eric Cayeux</Authors>
    <Company>NORCE Research</Company>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <UseLocalSemanticCatalogue Condition="'$(UseLocalSemanticCatalogue)' == '' and Exists('../../DotNetLibraries/OSDC.DotnetLibraries.General/OSDC.DotnetLibraries.Drilling.SemanticCatalogue/OSDC.DotnetLibraries.Drilling.SemanticCatalogue.csproj')">true</UseLocalSemanticCatalogue>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Condition="'$(UseLocalSemanticCatalogue)' == 'true'" Include="../../DotNetLibraries/OSDC.DotnetLibraries.General/OSDC.DotnetLibraries.Drilling.SemanticCatalogue/OSDC.DotnetLibraries.Drilling.SemanticCatalogue.csproj" />
    <PackageReference Condition="'$(UseLocalSemanticCatalogue)' != 'true'" Include="OSDC.DotnetLibraries.Drilling.SemanticCatalogue" Version="0.1.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GeographicLib.NET" Version="2.3.2" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\GravityModelFiles\**\*">
      <Link>GravityModelFiles\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
